### ISSUE TITLE
README lacks build instructions.

### ISSUE THREAD

**Issue by ptanmay143** [DjSt3rios/EZTVDownloader#2]
The `README.md` file in the repository mentions the usage of program but now how to actually build the program. This would be the step prior to getting the program running. Also called compiling the program. Hope I make myself clear.

**Comment by DjSt3rios** [comment]
You are absolutely right. I will add a few instructions for Visual Studio

**Comment by DjSt3rios** [comment]
Took me a while because I was busy, but I added basic instructions for Visual Studio 2019.
