### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Neon6784** [DjSt3rios/EZTVDownloader#3]
I got stuck at the 

'From the "Build" menu, click "Build solution"

I am no coder, so I understand that I need to follow the instruction as exactly as possible. 

But after I finish downloading and installing VS 2019, I follow the instruction until I reach this part. Initially can't find the 'Build' menu but soon found it after a quick google. 

But the option to "Build Solution" just wasn't there, it is still currently greyed out and I can't click it.

Any help would be appreciated

**Comment by DjSt3rios** [comment]
Hello my friend. Perhaps Visual Studio did not open the solution file automatically. Try the following:
Open the folder where the project is (I think by default this is under C:\Users\<your username\repos) and you should see a folder EZTVDownloader. In there, it should be a file EZTVDownload.sln, if you don't see file extensions, check it's Type, it should say Visual Studio Solution. Double click it, and Visual Studio should open the project solution. Then, the build solution option should be enabled. Let me know how it goes 😉

**Comment by Neon6784** [comment]
It helps,

Unfortunately, when I double-Clicked the .exe file in the folder, nothing shows up

As in literally, nothing happens, now what?

**Comment by DjSt3rios** [comment]
Hello, I suspect there is an error with the application, can you check the Event viewer? (Search for "Event Viewer" in windows search bar), check under Windows logs -> System or Application. To make it easier to search, double click the exe and then check the logs.

**Comment by Neon6784** [comment]
This is what I got, I just copy the details here

Log Name:      Application
Source:        Windows Error Reporting
Date:          6/11/2021 7:49:21 AM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      Mine

Description:
Fault bucket 2265775865467369810, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: EZTVDownloader.exe
P2: 1.1.0.0
P3: b6897a81
P4: Geckofx-Core
P5: 60.0.44.0
P6: 5dd5baa4
P7: 2d34
P8: b
P9: System.DllNotFoundException
P10: 

Attached files:
C:\Users\Users\AppData\Local\Temp\WER51FA.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users\Users\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_EZTVDownloader.e_bebeca1ed87495f116de6136c37de4487663e79_c4dcc165_0f9d56bc

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7916c237-ca46-11eb-8417-3010b3491170
Report Status: 0
Hashed bucket: 4b03f08081eaf1c32f71a72521d5f952
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-06-10T23:49:21.000000000Z" />
    <EventRecordID>79833</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Mine</Computer>
    <Security />
  </System>
  <EventData>
    <Data>2265775865467369810</Data>
    <Data>5</Data>
    <Data>CLR20r3</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>EZTVDownloader.exe</Data>
    <Data>1.1.0.0</Data>
    <Data>b6897a81</Data>
    <Data>Geckofx-Core</Data>
    <Data>60.0.44.0</Data>
    <Data>5dd5baa4</Data>
    <Data>2d34</Data>
    <Data>b</Data>
    <Data>System.DllNotFoundException</Data>
    <Data>
    </Data>
    <Data>
C:\Users\Users\AppData\Local\Temp\WER51FA.tmp.WERInternalMetadata.xml</Data>
    <Data>C:\Users\Users\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_EZTVDownloader.e_bebeca1ed87495f116de6136c37de4487663e79_c4dcc165_0f9d56bc</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>7916c237-ca46-11eb-8417-3010b3491170</Data>
    <Data>0</Data>
    <Data>4b03f08081eaf1c32f71a72521d5f952</Data>
  </EventData>
</Event>

**Comment by Neon6784** [comment]
This is also generated alongside it as well

Log Name:      Application
Source:        Application Error
Date:          6/11/2021 7:49:20 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Mine

Description:
Faulting application name: EZTVDownloader.exe, version: 1.1.0.0, time stamp: 0xb6897a81
Faulting module name: KERNELBASE.dll, version: 6.3.9600.19724, time stamp: 0x5ec50c3e
Exception code: 0xe0434352
Fault offset: 0x000156e8
Faulting process id: 0x5bc
Faulting application start time: 0x01d75e533b54c136
Faulting application path: C:\Users\Users\source\repos\EZTVDownloader\EZTVDownloader\bin\Debug\EZTVDownloader.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: 7916c237-ca46-11eb-8417-3010b3491170
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-06-10T23:49:20.000000000Z" />
    <EventRecordID>79832</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Mine</Computer>
    <Security />
  </System>
  <EventData>
    <Data>EZTVDownloader.exe</Data>
    <Data>1.1.0.0</Data>
    <Data>b6897a81</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.3.9600.19724</Data>
    <Data>5ec50c3e</Data>
    <Data>e0434352</Data>
    <Data>000156e8</Data>
    <Data>5bc</Data>
    <Data>01d75e533b54c136</Data>
    <Data>C:\Users\Users\source\repos\EZTVDownloader\EZTVDownloader\bin\Debug\EZTVDownloader.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\KERNELBASE.dll</Data>
    <Data>7916c237-ca46-11eb-8417-3010b3491170</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by DjSt3rios** [comment]
Well, there is a DLL missing, the question is, which one.. 🤔 Perhaps you can try to upgrade the .NET version. I will try to run the app myself today and see if it works right, maybe there is something missing

**Comment by DjSt3rios** [comment]
I found the issue. It was trying to load Firefox from the wrong folder. I pushed a new update, it should fix your problem :-)

**Comment by Neon6784** [comment]
> I found the issue. It was trying to load Firefox from the wrong folder. I pushed a new update, it should fix your problem :-)

It works as intended now, thanks for the help. Although I do apologize for the long period of time in replying back

The only issue I find so far is that currently, the Website for EZTV is https://eztv.wf/, not the .io that currently is the default for the program.

A way for us to change the default in case it changes again in the future would be appreciated but not currently an important issue

And thanks for putting up with me and creating/publishing this in the first place.

**Comment by DjSt3rios** [comment]
> > I found the issue. It was trying to load Firefox from the wrong folder. I pushed a new update, it should fix your problem :-)
> 
> It works as intended now, thanks for the help. Although I do apologize for the long period of time in replying back
> 
> The only issue I find so far is that currently, the Website for EZTV is https://eztv.wf/, not the .io that currently is the default for the program.
> 
> A way for us to change the default in case it changes again in the future would be appreciated but not currently an important issue
> 
> And thanks for putting up with me and creating/publishing this in the first place.

No problem at all. Assuming I don't forget, I will make a configuration for such settings 😊

**Comment by DjSt3rios** [comment]
I added a settings window, where you can change the initial URL, and I might add more in the future.
